# inherit_from: .rubocop_todo.yml

# inherit_from: .rubocop_todo.yml

# rubocop --auto-gen-config
# rubocop
# rubocop:disable all

#inherit_from: .rubocop_todo.yml

AllCops:
  Include:
#    - 'app/**/*.rb'
#    - 'bin/**/*.rb'
#    - 'config/**/*.rb'
#    - 'db/**/*.rb'
    - 'lib/**/*.rb'
    - 'test/**/*_test.rb'
    - '**/*.gemfile'
#    - '**/*.gemspec'
#    - '**/*.rake'
#    - '**/*.ru'
#    - '**/Gemfile'
#    - '**/Rakefile'
  Exclude:
#    - 'db/**/*'
#    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'gemfiles/*'
    - 'lib/{rows_controller}.rb'
    - 'lib/rows/{model,resources,utils}.rb'
    - 'test/**/*'
#    - !ruby/regexp /old_and_unused\.rb$/

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/AccessModifierIndentation:
  Enabled: false
Layout/AlignArray:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/IndentArray:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/Tab:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - 'test/**/*.rb'
Style/WhenThen:
  Exclude:
    - '.watchr'




