inherit_from:
  - ~/configs/.rubocop.yml

AllCops:
  Include:
    - 'lib/**/*.rb'
  Exclude:
    - 'test/**/*'

Layout/AccessModifierIndentation:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
