language: ruby
rvm:
#  - 2.0.0
#  - 2.2.0
  - 2.2.3

gemfile:
  - gemfiles/rails_4.2.4.gemfile
#  - gemfiles/rails-3.2.16.gemfile

matrix:
  include:
    - rvm: 2.0.0
      gemfiles/rails-3.2.16.gemfile
  exclude:
#    # rails 4.0 requries ruby 1.9.3 or newer
#    - rvm: 1.9.2
#      gemfile: gemfiles/rails-4.0.gemfile

notifications:
  email: false
