language: ruby
sudo: false
rvm:
#  - 2.0.0
  - 2.2.0
  - 1.9.3
  - 2.2.3

gemfile:
  - gemfiles/rails_4.2.4.gemfile
#  - gemfiles/rails-3.2.16.gemfile

matrix:
  include:
#    - rvm: 2.0.0
#      gemfile: gemfiles/rails-3.2.16.gemfile
  exclude:

notifications:
  email: false
