language: ruby
sudo: false

bundler_args: --without production
script: 'bundle exec rake test'

rvm:
  - 2.6.1
#  - 2.5.1
#  - 2.4.1
#  - 2.2.3
#  - 2.0.0

gemfile:
  - gemfiles/rails_5.2.gemfile
#  - gemfiles/rails_5.1.gemfile

matrix:
  fast_finish: true

notifications:
  email: false
